config/routes.rb
Rails.application.routes.draw do
  get 'reminders/index'
  get 'reminders/new'
  get 'reminders/edit'
  get 'reminders/update'
  get 'reminders/show'
  get 'reminders/destroy'
  get '/search', to:'reminders#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reminders#index"
  resources :reminders
  resources :reminder_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    enum status: [:active, :archived, :expired]
    belongs_to :reminder_type
    validates :status, presence: true
    validates :title, length: { minimum: 2 }, presence: true
    validates :content, length: { minimum: 5 }, presence: true
    validates :expire_at, presence: true
    validates :reminder_type_id, presence: true
end

app/models/reminder_type.rb
class ReminderType < ApplicationRecord
    has_many :reminder
    validates :name, length: { minimum: 2 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
end

app/controllers/reminder_types_controller.rb
class ReminderTypesController < ApplicationController

    def index
        @reminder_types = ReminderType.all
    end
    def edit
        @reminder_type = ReminderType.find(params[:id])
        render :edit
    end
    def update
        @reminder_type = ReminderType.find(params[:id])
        if @reminder_type.update(reminder_type_params)
            flash[:notice] = "Reminder type has been updated successfully"
            redirect_to "/reminders"
        else
            flash[:notice] = "Reminder type updation failed"
        end
    end
    def new
        @reminder_type = ReminderType.new
    end
    def show
        @reminder_type = ReminderType.find(params[:id])
    end
    def destroy
        @reminder_type = ReminderType.find(params[:id])

        if @reminder_type.destroy
            flash[:notice] = "Reminder type has been deleted successfully"
            redirect_to reminder_types_url
        else
            flash[:notice] = "Reminder type deletion failed"
        end
    end
    def create
        @reminder_type = ReminderType.new(reminder_type_params)

        if @reminder_type.save
            flash[:notice] = "Reminder type has been successfully added"
            redirect_to reminder_types_url
        else
            flash[:notice] = "Reminder type addition failed"
        end
    end

    private
        def set_reminder_type
            @reminder_type = ReminderType.find(params[:id])
        end
        def reminder_type_params
            params.require(:reminder_type).permit(:name)
        end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder_type, only: [:edit, :destroy, :update]

  def index
    @reminder = Reminder.all
  end

  def new
    @reminder = Reminder.new
  end

  def edit
    @reminder = Reminder.find(params[:id])
    render :edit
  end

  def update
    @reminder = Reminder.find(params[:id])
        if @reminder.update(reminders_params)
            flash[:notice] = "Reminder has been updated successfully"
            redirect_to reminders_url
        else
            flash[:notice] = "Reminder updation failed"
        end
  end

  def show
    @reminder = Reminder.find(params[:id])
  end

  def destroy
    @reminder = Reminder.find(params[:id])
        if @reminder.destroy
            flash[:notice] = "Reminder type has been deleted successfully"
            redirect_to reminders_url
        else
            flash[:notice] = "Reminder type deletion failed"
        end
  end
  def create
    @reminder = Reminder.new(reminders_params)

        if @reminder.save
            flash[:notice] = "Reminder type has been successfully added"
            redirect_to reminders_url
        else
            flash[:notice] = "Reminder type addition failed"
        end
  end
  
  def search
    @reminders = Reminder.where("title like ?","%"+params[:title]+"%")
  end

  private
        def set_reminder_type
            @reminder = Reminder.find(params[:id])
        end
        def reminders_params
            params.require(:reminder).permit(:title,:content,:expire_at,:status,:reminder_type_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminder_types_helper.rb
module ReminderTypesHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><em class="text-danger">Reminder</em> <i><strong>App</strong></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link <%= 'active' if controller_name=='reminders'%>" href="<%= reminders_path %>">Reminders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= 'active' if controller_name=='reminder_types'%>" href="<%= reminder_types_path %>">Reminder Type</a>
            </li>
        </ul>
      <%= form_with(:method=>"get",url: "/search", :class=>"d-flex") do |form|%>
        <%= form.text_field :title,:class=>"form-control me-2",:placeholder=>"Search title" %>
        <%= form.submit "Search",:class=>"btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemindersApp</title>
    <!-- CSS only -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% flash.each do |name,msg| %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong><%= msg %></strong>
        </div>
    <% end %>
    
    <%= render "common/navbar"%>

    <%= yield %>
  </body>
</html>

app/views/reminder_types/edit.html.erb
<div class="container-fluid col-6 mt-lg-4">
<%= form_with model: @reminder_type, url: reminder_type_path(@reminder_type) do |form| %>
  <div class="col-auto">
    <%= form.label :name, :class=>"form-label" %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>
  
  <div class="col-auto mt-lg-4">
    <%= form.submit "Edit",:class=>"btn btn-primary mb-3"%>
  </div>
<% end %>
</div>

app/views/reminder_types/index.html.erb
<div class="container-fluid col-6">
<%= link_to "new", new_reminder_type_url %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody><% c=0 %>
    <% @reminder_types.each do |t|%>
    <tr>
        <% c+=1 %>
      <th scope="row"><%= c %></th>
      <td><%= t.name %></td>
      <td><%= link_to "Edit","/reminder_types/#{t.id}/edit",:class=>"btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reminder_types/new.html.erb
<div class="container-fluid col-6 mt-lg-4">
<%= form_with model: @reminder_type, url: '/reminder_types' do |form| %>
  <div class="col-auto">
    <%= form.label :name, :class=>"form-label" %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>
  
  <div class="col-auto mt-lg-4">
    <%= form.submit "Create",:class=>"btn btn-primary mb-3"%>
  </div>
<% end %>
</div>

app/views/reminder_types/show.html.erb
<div class="container-fluid text-center col-8">
    <strong><p class="navbar-brand">Are you sure you want to delete reminder type!!</p></strong>
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div class="col-6">
            <%= @reminder_type.name %>
        </div>
        <div class="col-4">
            <%= button_to "Delete", reminder_type_path, method: :delete,:class=>"btn btn-danger" %>
        </div>
    </div>
</div>

app/views/reminders/edit.html.erb
<div class="container-fluid col-6 mt-lg-4">
<%= form_with model: @reminder, url: reminder_path(@reminder),method: :patch do |form| %>
  <div class="col-auto">
    <%= form.label :title, :class=>"form-label" %>
    <%= form.text_field :title, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :content, :class=>"form-label" %>
    <%= form.text_field :content, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :reminder_type_id, :class=>"form-label" %>
    <%= form.select :reminder_type_id, ReminderType.all.map{|rt| [rt.name,rt.id]},
    {prompt: "Please select reminder type"},{class: "form-control",placeholder: "Select"}%>
  </div>
  <div class="col-auto">
    <%= form.label :expire_at, :class=>"form-label" %>
    <%= form.datetime_field :expire_at, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :status, :class=>"form-label" %>
    <%= form.select :status, Reminder.statuses.map{|key,value| [key.titleize,key]},
    {prompt: "Please select reminder type"},{class: "form-control",placeholder: "Select"}%>
  </div>

  <div class="col-auto mt-lg-4">
    <%= form.submit "Edit",:class=>"btn btn-primary mb-3"%>
  </div>

<% end %>
</div>

app/views/reminders/index.html.erb
<div class="container-fluid col-8">
<%= link_to "new", new_reminder_url %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Reminder Type</th>
      <th scope="col">Expire At</th>
      <th scope="col">Status</th>
      <th scope="col">Delete/Edit</th>
    </tr>
  </thead>
  <tbody><% c=0 %>
    <% @reminder.each do |t|%>
    <tr>
        <% c+=1 %>
      <th scope="row"><%= c %></th>
      <td><%= t.title %></td>
      <td><%= t.content %></td>
      <td><%= ReminderType.find(t.reminder_type_id).name %></td>
      <td><%= t.expire_at %></td>
      <td><%= t.status %></td>
      <td><%= link_to "Delete", "reminders/#{t.id}" ,method: :delete, :class=>"btn btn-danger" %> <%= link_to "Edit", "reminders/#{t.id}/edit" ,method: :delete, :class=>"btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reminders/new.html.erb
<div class="container-fluid col-6 mt-lg-4">
<%= form_with model: @reminder, url: '/reminders' do |form| %>
  <div class="col-auto">
    <%= form.label :title, :class=>"form-label" %>
    <%= form.text_field :title, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :content, :class=>"form-label" %>
    <%= form.text_field :content, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :reminder_type_id, :class=>"form-label" %>
    <%= form.select :reminder_type_id, ReminderType.all.map{|rt| [rt.name,rt.id]},
    {prompt: "Please select reminder type"},{class: "form-control",placeholder: "Select"}%>
  </div>
  <div class="col-auto">
    <%= form.label :expire_at, :class=>"form-label" %>
    <%= form.datetime_field :expire_at, :class=>"form-control" %>
  </div>
  <div class="col-auto">
    <%= form.label :status, :class=>"form-label" %>
    <%= form.select :status, Reminder.statuses.map{|key,value| [key.titleize,key]},
    {prompt: "Please select reminder type"},{class: "form-control",placeholder: "Select"}%>
  </div>

  <div class="col-auto mt-lg-4">
    <%= form.submit "Create",:class=>"btn btn-primary mb-3"%>
  </div>

<% end %>
</div>

app/views/reminders/search.html.erb
<div class="container-fluid col-8">
<%= link_to "new", new_reminder_url %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Reminder Type</th>
      <th scope="col">Expire At</th>
      <th scope="col">Status</th>
      <th scope="col">Delete/Edit</th>
    </tr>
  </thead>
  <tbody><% c=0 %>
    <% @reminders.each do |t|%>
    <tr>
        <% c+=1 %>
      <th scope="row"><%= c %></th>
      <td><%= t.title %></td>
      <td><%= t.content %></td>
      <td><%= ReminderType.find(t.reminder_type_id).name %></td>
      <td><%= t.expire_at %></td>
      <td><%= t.status %></td>
      <td><%= link_to "Delete", "reminders/#{t.id}" ,method: :delete, :class=>"btn btn-danger" %> <%= link_to "Edit", "reminders/#{t.id}/edit" ,method: :delete, :class=>"btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reminders/show.html.erb
<div class="container-fluid text-center col-8">
    <strong><p class="navbar-brand">Are you sure you want to delete reminder!!</p></strong>
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div class="col-6">
            <%= @reminder.title %>
        </div>
        <div class="col-4">
            <%= button_to "Delete", reminder_path, method: :delete,:class=>"btn btn-danger" %>
        </div>
    </div>
</div>